### ISSUE TITLE
16.17-rearrange-arguments.hs question 3 does not pass test

### ISSUE THREAD

**Issue by krpot** [larrybotha/haskell-book#10]
First of all, thank you very much for your awesome job and it helps me a lot. I found a small thing needs to be slightly fixed.
 
```
data More a b = La b a | R b a b deriving (Eq, Show)
```
Your implementation:
```
instance Functor (More x) where
    fmap f (L a b a') = L (f a) b (f a') 
    fmap f (R b a b') = R b (f a) b'
```
This does not pass the test in the book:
```
Prelude> fmap (+1) (L 1 2 3)
L 2 2 4 -- your answer L 1 3 3
Prelude> fmap (+1) (R 1 2 3) 
R 1 3 3 -- your answer R 2 2 4
```

So, both data type and Functor should be changed:
```
data More a b = L b a b | R a b a deriving (Eq, Show)
instance Functor (More x) where
    fmap f (L b a b') = L (f b) a (f b')
    fmap f (R a b a') = R a (f b) a'
```

Thanks.

**Comment by larrybotha** [comment]
excellent, thanks for the heads up @krpot. Fixed in https://github.com/larrybotha/haskell-book/commit/4bfc38975678be607a5a19cea18a38c4ecc059ec
