### ISSUE TITLE
Possible mistake 12.5 rights' code

### ISSUE THREAD

**Issue by agivney** [larrybotha/haskell-book#13]
Thank you for the great work you have done. It has been a life saver.

I found this following snippet from exercise 12.5 would not compile, due to the return type being marked as [a] `instead` of [b].

Does not compile:
```

rights' :: [Either a b] -> [a]
rights' xs = foldr next [] xs
  where
    next (Right v) vals = v : vals
    next _ vals = vals
```

Does compile:
```
rights' :: [Either a b] -> [b]
rights' xs = foldr next [] xs
  where
    next (Right v) vals = v : vals
    next _ vals = vals

```

**Comment by larrybotha** [comment]
@agivney this looks correct - `b` is of type `Right` :D
